// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://g3r3umw6v5dylh2m4nyj4yotee.appsync-api.eu-north-1.amazonaws.com/graphql',
          region: 'eu-north-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-lrlomfl4knakdnjd6wzftzrif4'
        }
    }
};

export default config;