// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
  API: {
      GraphQL: {
        endpoint: 'https://h2s3lp2wljcalh2rw62ruo5oby.appsync-api.us-east-1.amazonaws.com/graphql',
        region: 'us-east-1',
        defaultAuthMode: 'apiKey',
        apiKey: 'da2-2pyf6i2p7bgkzargzz2grmmfqm'
      }
  }
};

export default config;